### ISSUE TITLE
Presets are not being passed properly to vueify

### ISSUE THREAD

**Issue by srodriki** [nblackburn/vue-brunch#17]
I've been using vue-brunch and got into the need to use vuex's mapGetters helper method, which in turn requires babel's transform-rest-object-spread plugin to work. It appears that, even though I was passing babel's "stage-3" preset as part of brunch's plugin config, vue-brunch is not passing said option to vueify, so I was forced to add a .babelrc with my options, forcing vueify to see it. 

I'm not sure if this is a vue-brunch bug per se, as it might be vueify does not offer any interface to pass it babel plugins or presets other than via a .babelrc file.

Yet, I'd like to at least leave this reported here in case someone else stumbles upon this very same issue. 

I know @nblackburn is working on a rewrite of this plugin and dropping vueify dependencies while at that, so this will certainly be solved then. However, until that happens, please be aware you will still need the .babelrc file with your babel presets and plugins for vueify to play nice along with brunch.

**Comment by jkruse** [comment]
Only the "plugins.vue" part of the Brunch Config is passed to vueify, which kind of makes sense. I worked around this problem by added this to the bottom of my brunch-config.js:

```javascript
// Pass Babel config to Vue
exports.plugins.vue = exports.plugins.vue || {};
exports.plugins.vue.babel = exports.plugins.babel || {};
```

**Comment by nblackburn** [comment]
I don't think this is a problem personally, you can pass the babel config via `plugins.vue.babel` as you would expect. The only issue is i guess the potential for having to duplicate the config but at the same time, you might want a slightly different config.
