### ISSUE TITLE
Error while running brunch

### ISSUE THREAD

**Issue by imetallica** [nblackburn/vue-brunch#18]
Hi, I'm having this issue when trying to use `vue-brunch`:

I'm using `brunch: 2.7.5`.

```
25 Feb 09:58:28 - error: Initialization error -  Cannot read property 'brunchPluginName' of null
Type  at loadPackages.filter.arg (/home/imetallica/Projects/Lugik/lugik/node_modules/brunch/lib/plugins.js:140:33)
  at Array.filter (native)
  at Object.exports.init (/home/imetallica/Projects/Lugik/lugik/node_modules/brunch/lib/plugins.js:139:38)
  at BrunchWatcher.application.loadConfig.then.then.then.cfg (/home/imetallica/Projects/Lugik/lugik/node_modules/brunch/l
ib/watch.js:112:19)
```

**Comment by nblackburn** [comment]
I will take a look at this tonight, sorry for the delay.

**Comment by imetallica** [comment]
@nblackburn , I figured out just now what was the problem. I had to remove and do a new `npm install`. Sorry not reaching you soon, but this was a project I had to put on hold for a while and just now got it back on it.

**Comment by nblackburn** [comment]
@imetallica no worries, thanks for updating me on this.
