### ISSUE TITLE
Consider bumping version

### ISSUE THREAD

**Issue by 1player** [nblackburn/vue-brunch#2]
Commit fdc675e upgraded a few dependencies, including vueify 9.2.3 required to use Vue 2.0, but hasn't bumped the package version.

The only way to use vue-brunch with Vue 2.0 support is to install it from git.

Please consider bumping the vue-brunch version and publishing it.

**Comment by nblackburn** [comment]
Sorry about this, i have a lot of repos to maintain so tend to do development in waves. I will get right on this once i get back from work.

**Comment by nblackburn** [comment]
Upon closer inspection, it would be better to maintain support for 1.x for the time being (allowing time for people to migrate) so will start working on a 2.x branch instead.

**Comment by nblackburn** [comment]
I have reverted these changes for now, i will keep you posted.

**Comment by 1player** [comment]
Don’t quote me on that, but the new vueify is compatible with both 1.x and
2.x.

The problem with the published version is that it is not compatible with
2.x, so publishing the package with upgraded deps is a win-win.


On 16 August 2016 at 14:30:22, Nathaniel Blackburn (notifications@github.com)
wrote:

Upon closer inspection, it would be better to maintain support for 1.x for
the time being (allowing time for people to migrate) so will start working
on a 2.x branch instead.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nblackburn/vue-brunch/issues/2#issuecomment-240100420>,
or mute the thread

**Comment by 1player** [comment]
Please don't revert the changes, or move them in a separate branch at least, or I can't use this package with vue 2.0 anymore and my code is broken.

**Comment by nblackburn** [comment]
Updated master with 1.x changes and created a dev branch which has updates for 2.x.
