### ISSUE TITLE
Single file components: changes on external stylus templates not being watched

### ISSUE THREAD

**Issue by nicooga** [nblackburn/vue-brunch#23]
I'm using external stylus templates this way:

~~~vue
<template lang='pug'>
  // ...
</template>

<script>
  export default {}
</script>

<style lang='stylus'>
  @import "./_style.styl"
</style>
~~~

It works fine but each time I modify the external stylus template I have to restart the server because it doesn't detect the changes to the style.

Not using a partial (by not prefixing the template with "_")  doesn't help. But doing that also means the file would get compiled and joined to something like "app.css", putting the styles in the global scope.

**Comment by theocodes** [comment]
@nicooga Could you pls confirm this is still an issue? I've just taken over the project and will be looking at addressing issues but want to confirm they're still valid. 

Thanks

**Comment by wesssel** [comment]
+1 👍
