### ISSUE TITLE
need to use require in index.html

### ISSUE THREAD

**Issue by lil5** [nblackburn/vue-brunch#24]
I strangely need to add 
`<script type="text/javascript">
		require('main.js');
	</script>`
for things to work 
why?

**Comment by riri** [comment]
Because brunch does not use an entry point by default, it just bundles your sources.

If you want your main js to be sources when the bundle is required, use the autoRequire in your brunch-config.js like explained [here](http://brunch.io/docs/config#-modules-).

For example:
```
{
  // ...
  modules: {
    autoRequire: {
      'app.js': [ 'application.js' ]
    }
  },
  // ...
}

```

**Comment by lil5** [comment]
*Thanks so much!*
You've saved me hour of swearing at webpack
