### ISSUE TITLE
Sourcemaps does not work

### ISSUE THREAD

**Issue by StarpTech** [nblackburn/vue-brunch#32]
1. Check [this](https://github.com/netzkern/brunch-demo) out
2. Insert `debugger` [here](https://github.com/netzkern/brunch-demo/blob/master/app/components/Hello.vue#L11) and you will see `var` instead `const` + many transpiled code.

**Comment by nblackburn** [comment]
Closing this because your code seems to have changed so i assume this is no longer an issue.
