### ISSUE TITLE
Support for i18n blocks (and other custom blocks?) in single component files

### ISSUE THREAD

**Issue by stephenhoward** [nblackburn/vue-brunch#34]
vue-i18n is a popular enough plugin to get mention in the official vue documentation.  This plugin suggests using custom i18n blocks in single-file vue components to hold translated strings.  It would be good to be able to access these blocks under brunch.

**Comment by nblackburn** [comment]
The custom blocks in vue-i18n requires https://github.com/kazupon/vue-i18n-loader which is a webpack plugin.
