### ISSUE TITLE
Support for Vue 2.0

### ISSUE THREAD

**Issue by nblackburn** [nblackburn/vue-brunch#4]
Add support for the soon to be released Vue 2.0.

**Comment by nblackburn** [comment]
You may have noticed a experimental release (1.2.1) recently which has support for Vue 2.0 but an issue with Brunch prevents it from working as intended.

Brunch doesn't support converting process variables other than `NODE_ENV` which Vue 2.0 has recently started using.

https://github.com/brunch/brunch/issues/1510

**Comment by JohnnyCrazy** [comment]
@nblackburn I ran into the same issue on windows today. But it seems like it's a windows only problem. I'm running the exact same code on linux successfully. But sadly I couldn't track why it happens, the object `process` is just missing :/

Arch-Linux:
![img](http://i.imgur.com/yozbD7M.png)

Windows:
![img](http://i.imgur.com/ZXcBd95.png)

**Comment by nblackburn** [comment]
@JohnnyCrazy What version of Vue are you using?

**Comment by nblackburn** [comment]
@JohnnyCrazy Do you see an error on the browser console regarding process?

**Comment by JohnnyCrazy** [comment]
@nblackburn On windows, yes, it's just says `process is undefined`. On linux, no, the Vue-App runs without problems (you can see that `process` exists in the first screenshot on the right side).

**Comment by nblackburn** [comment]
@JohnnyCrazy I am aware of the issue and think it's related to Brunch only replacing `process.env.NODE_ENV` leaving the recently introduced `process.env.VUE_ENV` as is which is obviously not right.

**Comment by JohnnyCrazy** [comment]
But why should it work when brunch is run under Linux?

**Comment by JohnnyCrazy** [comment]
I still can't believe it's a platform issue, will do some more testing tomorrow

**Comment by nblackburn** [comment]
@JohnnyCrazy Not entirely sure as has been consistent on Mac and Windows but haven't been able to test it on Linux so it comes across as strange how it behaves differently there.

**Comment by Gangwolf** [comment]
I been having the same problem too. I run brunch under Windows and I get a `process is undefined` console error, but when I run the same project under WSL (Bash on Ubuntu on Windows) it works.

**Comment by JohnnyCrazy** [comment]
Hah @Gangwolf, thanks for having my back here :P already thought I did something wrong with some versions or similar

**Comment by nblackburn** [comment]
@JohnnyCrazy I am certain it's Brunch as that handles the shimming of process variables.

**Comment by JohnnyCrazy** [comment]
Found it after tracing back about 10 files :sweat_smile: 

The problem is [here(1)](https://github.com/brunch/node-browser-modules/blob/master/index.js) and [here(2)](https://github.com/brunch/deppack/blob/fad549bb6a95ce258f658bb64951cdfad250a55f/lib/shims.js#L20)

So this is how `process` looks like in (1):
```
...
process: 'e:\\Programmierung\\Projekte\\odin\\node_modules\\process\\browser.js'
...
```

And this is how `isFileShim` gets it in (2):
```
'e:/Programmierung/Projekte/odin/node_modules/process/browser.js'
```

So basically it doesn't get recognized as shim because `node-browser-modules` adds `\\` while `deppack` is using single `/`.

So we need to find a way to convert them somehow

**Comment by nblackburn** [comment]
Great detective work there @JohnnyCrazy, thanks for your hard work.

I had a feeling it would be a pathing issue as I have had similar issues with Brunch before on Windows.

**Comment by JohnnyCrazy** [comment]
Since I doubt there will be much activity in those repos, I made a quick fix myself in [JohnnyCrazy/node-browser-modules#windowsFix](https://github.com/JohnnyCrazy/node-browser-modules/tree/windowsFix).

Although it's not a final solution, feel free to add them to your projects:
```
npm install JohnnyCrazy/node-browser-modules#windowsFix --save
```
`node-browser-modules` was last updated around january, we should be fine for some time.

@nblackburn  @Gangwolf

**Comment by kevin-DL** [comment]
Hello, i am trying to use the common eventHub in vue2.0. Do you know how i would need to configure my files for it to work?

Cheers,
Kevin

**Comment by nblackburn** [comment]
@kevin-DL Could i ask if this is related to vue-brunch or a question in general?

**Comment by kevin-DL** [comment]
@nblackburn Thing is i am not sure at the moment if it would be specific to vue-brunch or not.

**Comment by nblackburn** [comment]
@kevin-DL No worries, it sounds like a general question for Vue 2.0 but am happy to help with that.

In Vue 2.0, events are handled simply by creating a new Vue instance.

```javascript
const eventDispatcher = new Vue();
```

From there, you can use `$emit` to trigger events,  and `$on` or `$off` to handle them, like so...

```javascript
event.$emit('user.signin', {username: 'nblackburn'});
```

```javascript
event.$on('user.signin', (user) => {
    console.log(`Hello, ${user.username}`);
});
```

**Comment by kevin-DL** [comment]
@nblackburn Thanks a lot.
This far i haven't had any real problem using vue-brunch with vue2.0

**Comment by nblackburn** [comment]
@kevin-DL Thanks, as far as i am aware, it's only an issue on Windows which i am waiting for a fix on before i am confident to wrap it up and move the 1.x build to another branch.

**Comment by kevin-DL** [comment]
@nblackburn Cool. Good luck on that

**Comment by nblackburn** [comment]
Finally got a response to fix it myself...

**Comment by nblackburn** [comment]
OK, so i got a reply from Paul  basically telling me to fix it myself. I used my skeleton for brunch and vue as the base for my experiments and found that process was in fact being populated in the final build however not for files containing VUE_ENV.

I will look into this more this evening and report my findings.

**Comment by JohnnyCrazy** [comment]
Any news @nblackburn ? :pray:

**Comment by nblackburn** [comment]
@JohnnyCrazy Nope, at the very least i need a post-compile hook to replace VUE_ENV in files i can't access in compile time.

**Comment by nblackburn** [comment]
@JohnnyCrazy Forgot to mention that i incorporated your changes into a dev release.

**Comment by JohnnyCrazy** [comment]
Alright, gonna do some testing today then! 👍

**Comment by JohnnyCrazy** [comment]
Whoop Whoop, seems to work fine on windows/linux 🎉 

![](http://i.imgur.com/RJaL7aJ.png)
