### ISSUE TITLE
Very summary example of usage for Vue 2.0

### ISSUE THREAD

**Issue by mos8580** [nblackburn/vue-brunch#9]
Hi,

I'm new to both Phoenix, brunch and Vue, and I was wondering if there was a very simple how-to to get an "Hello World!" on screen with Vue 2.0 and components from a new Phoenix project.

I was thinking something akin to [this](https://medium.com/front-end-hacking/phoenix-and-vue-js-b974d8b91cb6#.nsgbph18y) that used to work for Vue 1.x.

Apologies in advance if this is obvious...

Thanks!

**Comment by nblackburn** [comment]
I have never used Phoenix before to be honest.

**Comment by mos8580** [comment]
I was a bit hasty and now realize this project is not related to Phoenix in any way, shape or form! Apologies...

**Comment by nblackburn** [comment]
@mos8580 It's alright, happy to help :)
